/**
 * lha-lookup.js — Local Housing Allowance rate lookup by postcode.
 *
 * GET /.netlify/functions/lha-lookup?postcode=LS1+1AA&age=25+to+34&children=No+children&situation=Unemployed
 *
 * Returns:
 *   { postcode, councilName, brma, lhaMonthly, bedroomCat, found, region }
 *
 * Data source: GOV.UK 2026/27 LHA rates Table 4 (weekly → monthly ×52/12).
 * Postcode → LA:  postcodes.io (free, no API key).
 * LA → BRMA:      manual mapping covering ~250 LAs.
 */

// ---------------------------------------------------------------------------
// 2026/27 LHA rates — weekly figures converted to monthly (×52/12, 2dp)
// CAT A = shared accommodation | B = 1-bed | C = 2-bed | D = 3-bed | E = 4-bed
// ---------------------------------------------------------------------------
const BRMA_RATES = {
  'Ashford':                    { shared:392.17,  onebed:747.93,   twobed:847.69,   threebed:1094.77,  fourbed:1436.07  },
  'Aylesbury':                  { shared:441.44,  onebed:797.81,   twobed:992.29,   threebed:1326.35,  fourbed:1645.5   },
  'Barnsley':                   { shared:315.47,  onebed:413.88,   twobed:448.76,   threebed:548.51,   fourbed:772.89   },
  'Barrow-in-Furness':          { shared:394.33,  onebed:473.72,   twobed:498.64,   threebed:633.27,   fourbed:805.31   },
  'Basingstoke':                { shared:405.21,  onebed:777.88,   twobed:947.4,    threebed:1146.86,  fourbed:1396.16  },
  'Bath':                       { shared:538.5,   onebed:812.76,   twobed:977.3,    threebed:1196.69,  fourbed:1939.69  },
  'Bedford':                    { shared:448.76,  onebed:648.22,   twobed:822.73,   threebed:997.27,   fourbed:1296.45  },
  'Birmingham':                 { shared:340.64,  onebed:693.12,   twobed:747.93,   threebed:822.73,   fourbed:1096.98  },
  'Black Country':              { shared:319.11,  onebed:493.65,   twobed:623.31,   threebed:747.93,   fourbed:922.48   },
  'Blackwater Valley':          { shared:476.67,  onebed:797.81,   twobed:997.27,   threebed:1291.46,  fourbed:1695.33  },
  'Bolton and Bury':            { shared:340.56,  onebed:473.72,   twobed:573.43,   threebed:698.1,    fourbed:947.4    },
  'Bournemouth':                { shared:425.14,  onebed:693.12,   twobed:872.6,    threebed:1146.86,  fourbed:1545.74  },
  'Bradford & South Dales':     { shared:325.43,  onebed:448.76,   twobed:523.55,   threebed:633.27,   fourbed:747.93   },
  'Brighton and Hove':          { shared:585.0,   onebed:917.5,    twobed:1196.69,  threebed:1446.03,  fourbed:1994.5   },
  'Bristol':                    { shared:509.95,  onebed:897.52,   twobed:1092.0,   threebed:1296.45,  fourbed:1844.92  },
  'Bury St Edmunds':            { shared:450.1,   onebed:628.29,   twobed:772.89,   threebed:952.38,   fourbed:1296.45  },
  'Cambridge':                  { shared:524.9,   onebed:897.52,   twobed:947.4,    threebed:1121.9,   fourbed:1446.03  },
  'Canterbury':                 { shared:423.84,  onebed:673.14,   twobed:892.54,   threebed:1096.98,  fourbed:1311.4   },
  'Central Greater Manchester': { shared:410.45,  onebed:772.89,   twobed:872.6,    threebed:947.4,    fourbed:1346.28  },
  'Central Lancs':              { shared:303.33,  onebed:448.76,   twobed:573.43,   threebed:648.22,   fourbed:922.48   },
  'Central London':             { shared:827.54,  onebed:1436.02,  twobed:1789.06,  threebed:2154.1,   fourbed:3051.62  },
  'Central Norfolk & Norwich':  { shared:392.43,  onebed:588.38,   twobed:693.12,   threebed:797.81,   fourbed:1146.86  },
  'Chelmsford':                 { shared:425.14,  onebed:792.83,   twobed:947.4,    threebed:1196.69,  fourbed:1446.03  },
  'Cheltenham':                 { shared:435.28,  onebed:623.31,   twobed:797.81,   threebed:997.27,   fourbed:1465.97  },
  'Cherwell Valley':            { shared:465.23,  onebed:772.89,   twobed:947.4,    threebed:1181.74,  fourbed:1446.03  },
  'Chesterfield':               { shared:350.35,  onebed:448.76,   twobed:523.55,   threebed:598.35,   fourbed:847.69   },
  'Chichester':                 { shared:448.76,  onebed:785.85,   twobed:947.4,    threebed:1221.65,  fourbed:1595.62  },
  'Chilterns':                  { shared:523.55,  onebed:847.69,   twobed:1096.98,  threebed:1446.03,  fourbed:1994.5   },
  'Colchester':                 { shared:400.23,  onebed:623.31,   twobed:792.83,   threebed:972.31,   fourbed:1246.57  },
  'Coventry':                   { shared:431.17,  onebed:573.43,   twobed:673.14,   threebed:772.89,   fourbed:997.27   },
  'Crawley & Reigate':          { shared:475.02,  onebed:857.65,   twobed:1096.98,  threebed:1361.27,  fourbed:1745.21  },
  'Darlington':                 { shared:288.17,  onebed:359.02,   twobed:448.76,   threebed:528.54,   fourbed:693.12   },
  'Derby':                      { shared:358.84,  onebed:448.76,   twobed:593.36,   threebed:698.1,    fourbed:932.45   },
  'Doncaster':                  { shared:303.33,  onebed:423.84,   twobed:498.64,   threebed:548.51,   fourbed:723.02   },
  'Dover-Shepway':              { shared:430.3,   onebed:508.6,    twobed:693.12,   threebed:862.64,   fourbed:1196.69  },
  'Durham':                     { shared:392.17,  onebed:392.17,   twobed:398.88,   threebed:473.72,   fourbed:658.06   },
  'East Cheshire':              { shared:420.33,  onebed:548.51,   twobed:723.02,   threebed:992.29,   fourbed:1745.21  },
  'East Lancs':                 { shared:290.68,  onebed:423.84,   twobed:473.72,   threebed:593.36,   fourbed:792.83   },
  'East Thames Valley':         { shared:589.9,   onebed:897.52,   twobed:1196.69,  threebed:1446.03,  fourbed:1894.79  },
  'Eastbourne':                 { shared:421.33,  onebed:718.03,   twobed:897.52,   threebed:1080.04,  fourbed:1396.16  },
  'Eastern Staffordshire':      { shared:320.45,  onebed:493.65,   twobed:598.35,   threebed:723.02,   fourbed:983.1    },
  'Exeter':                     { shared:535.51,  onebed:628.29,   twobed:792.83,   threebed:947.4,    fourbed:1296.45  },
  'Fylde Coast':                { shared:349.92,  onebed:398.88,   twobed:540.5,    threebed:623.31,   fourbed:740.48   },
  'Gloucester':                 { shared:405.21,  onebed:548.51,   twobed:723.02,   threebed:847.69,   fourbed:1196.69  },
  'Grantham & Newark':          { shared:375.31,  onebed:423.84,   twobed:573.43,   threebed:653.21,   fourbed:872.6    },
  'Greater Liverpool':          { shared:343.42,  onebed:498.64,   twobed:593.36,   threebed:648.22,   fourbed:872.6    },
  'Grimsby':                    { shared:316.33,  onebed:393.9,    twobed:478.7,    threebed:520.0,    fourbed:718.03   },
  'Guildford':                  { shared:513.59,  onebed:947.4,    twobed:1221.65,  threebed:1475.93,  fourbed:1972.58  },
  'Halifax':                    { shared:355.33,  onebed:438.79,   twobed:523.55,   threebed:623.31,   fourbed:747.93   },
  'Harlow & Stortford':         { shared:450.1,   onebed:807.78,   twobed:1022.19,  threebed:1206.7,   fourbed:1371.24  },
  'Harrogate':                  { shared:420.16,  onebed:593.36,   twobed:733.85,   threebed:872.6,    fourbed:1271.49  },
  'Herefordshire':              { shared:350.52,  onebed:473.72,   twobed:598.35,   threebed:747.93,   fourbed:972.31   },
  'High Weald':                 { shared:458.55,  onebed:797.81,   twobed:1072.07,  threebed:1319.37,  fourbed:1820.0   },
  'Hull & East Riding':         { shared:334.92,  onebed:378.95,   twobed:473.72,   threebed:548.51,   fourbed:698.1    },
  'Huntingdon':                 { shared:458.73,  onebed:648.22,   twobed:792.83,   threebed:947.4,    fourbed:1246.57  },
  'Inner East London':          { shared:697.58,  onebed:1436.02,  twobed:1745.21,  threebed:2154.1,   fourbed:2991.78  },
  'Inner North London':         { shared:706.33,  onebed:1436.02,  twobed:1789.06,  threebed:2154.1,   fourbed:3051.62  },
  'Inner South East London':    { shared:648.22,  onebed:1291.98,  twobed:1545.74,  threebed:1944.67,  fourbed:2617.81  },
  'Inner South West London':    { shared:683.11,  onebed:1416.09,  twobed:1695.33,  threebed:2154.1,   fourbed:2892.07  },
  'Inner West London':          { shared:757.9,   onebed:1346.28,  twobed:1620.54,  threebed:2044.38,  fourbed:2543.02  },
  'Ipswich':                    { shared:365.52,  onebed:593.36,   twobed:715.04,   threebed:797.81,   fourbed:1096.98  },
  'Isle of Wight':              { shared:342.33,  onebed:513.59,   twobed:648.22,   threebed:812.76,   fourbed:992.29   },
  'Kendal':                     { shared:325.0,   onebed:573.43,   twobed:648.22,   threebed:772.89,   fourbed:992.29   },
  'Kernow West':                { shared:391.43,  onebed:548.51,   twobed:693.12,   threebed:812.76,   fourbed:1096.98  },
  'Kings Lynn':                 { shared:398.75,  onebed:546.74,   twobed:648.22,   threebed:772.89,   fourbed:1047.11  },
  'Kirklees':                   { shared:315.47,  onebed:448.76,   twobed:523.55,   threebed:648.22,   fourbed:822.73   },
  'Lancaster':                  { shared:393.25,  onebed:473.72,   twobed:573.43,   threebed:648.22,   fourbed:723.02   },
  'Leeds':                      { shared:346.67,  onebed:673.14,   twobed:772.89,   threebed:847.69,   fourbed:1196.69  },
  'Leicester':                  { shared:394.33,  onebed:538.5,    twobed:648.22,   threebed:772.89,   fourbed:1047.11  },
  'Lincoln':                    { shared:353.17,  onebed:493.65,   twobed:598.35,   threebed:673.14,   fourbed:922.48   },
  'Lincolnshire Fens':          { shared:367.34,  onebed:498.64,   twobed:623.31,   threebed:732.98,   fourbed:862.68   },
  'Lowestoft & Great Yarmouth': { shared:375.31,  onebed:439.88,   twobed:573.43,   threebed:628.29,   fourbed:822.73   },
  'Luton':                      { shared:434.98,  onebed:698.1,    twobed:872.6,    threebed:1096.98,  fourbed:1346.28  },
  'Maidstone':                  { shared:443.6,   onebed:747.93,   twobed:902.5,    threebed:1196.69,  fourbed:1545.74  },
  'Medway & Swale':             { shared:408.89,  onebed:673.14,   twobed:847.69,   threebed:937.43,   fourbed:1296.45  },
  'Mendip':                     { shared:403.91,  onebed:598.35,   twobed:772.89,   threebed:972.31,   fourbed:1346.28  },
  'Mid & East Devon':           { shared:403.0,   onebed:528.54,   twobed:683.11,   threebed:822.73,   fourbed:1096.98  },
  'Mid & West Dorset':          { shared:425.14,  onebed:593.36,   twobed:747.93,   threebed:897.52,   fourbed:1246.57  },
  'Mid Staffs':                 { shared:351.43,  onebed:498.64,   twobed:623.31,   threebed:737.97,   fourbed:992.29   },
  'Milton Keynes':              { shared:499.94,  onebed:772.89,   twobed:922.48,   threebed:1191.71,  fourbed:1490.88  },
  'Newbury':                    { shared:450.1,   onebed:747.93,   twobed:892.54,   threebed:1196.69,  fourbed:1600.6   },
  'North Cheshire':             { shared:340.56,  onebed:473.72,   twobed:588.38,   threebed:693.12,   fourbed:997.27   },
  'North Cornwall & Devon Borders': { shared:367.34, onebed:473.72, twobed:607.32,  threebed:723.02,   fourbed:947.4    },
  'North Cumbria':              { shared:318.93,  onebed:393.9,    twobed:473.72,   threebed:588.38,   fourbed:737.97   },
  'North Devon':                { shared:423.84,  onebed:483.69,   twobed:643.24,   threebed:772.89,   fourbed:992.29   },
  'North Nottingham':           { shared:338.0,   onebed:443.78,   twobed:548.51,   threebed:583.4,    fourbed:807.78   },
  'North West Kent':            { shared:450.1,   onebed:747.93,   twobed:992.29,   threebed:1196.69,  fourbed:1446.03  },
  'North West London':          { shared:619.62,  onebed:1096.98,  twobed:1346.28,  threebed:1675.4,   fourbed:2094.26  },
  'Northampton':                { shared:409.5,   onebed:643.24,   twobed:747.93,   threebed:897.52,   fourbed:1156.83  },
  'Northants Central':          { shared:374.83,  onebed:548.51,   twobed:693.12,   threebed:792.83,   fourbed:992.29   },
  'Northumberland':             { shared:355.33,  onebed:373.97,   twobed:423.84,   threebed:528.54,   fourbed:757.9    },
  'Nottingham':                 { shared:378.95,  onebed:548.51,   twobed:648.22,   threebed:747.93,   fourbed:967.33   },
  'Oldham & Rochdale':          { shared:343.89,  onebed:473.72,   twobed:575.94,   threebed:693.12,   fourbed:947.4    },
  'Outer East London':          { shared:559.78,  onebed:1196.69,  twobed:1396.16,  threebed:1670.41,  fourbed:1944.67  },
  'Outer North East London':    { shared:548.34,  onebed:997.27,   twobed:1246.57,  threebed:1495.91,  fourbed:1795.08  },
  'Outer North London':         { shared:593.36,  onebed:1146.86,  twobed:1396.16,  threebed:1690.35,  fourbed:2193.97  },
  'Outer South East London':    { shared:598.35,  onebed:1047.11,  twobed:1296.45,  threebed:1545.74,  fourbed:1795.08  },
  'Outer South London':         { shared:567.75,  onebed:947.4,    twobed:1196.69,  threebed:1495.91,  fourbed:1944.67  },
  'Outer South West London':    { shared:589.9,   onebed:1196.69,  twobed:1490.88,  threebed:1795.08,  fourbed:2543.02  },
  'Outer West London':          { shared:574.73,  onebed:997.27,   twobed:1296.45,  threebed:1470.95,  fourbed:1795.08  },
  'Oxford':                     { shared:548.51,  onebed:897.52,   twobed:1121.9,   threebed:1321.36,  fourbed:1745.21  },
  'Peaks & Dales':              { shared:346.67,  onebed:473.72,   twobed:593.36,   threebed:693.12,   fourbed:897.52   },
  'Peterborough':               { shared:343.89,  onebed:573.43,   twobed:698.1,    threebed:807.78,   fourbed:1047.11  },
  'Plymouth':                   { shared:398.88,  onebed:548.51,   twobed:673.14,   threebed:797.81,   fourbed:972.31   },
  'Portsmouth':                 { shared:421.68,  onebed:693.12,   twobed:842.7,    threebed:997.27,   fourbed:1296.45  },
  'Reading':                    { shared:390.43,  onebed:847.69,   twobed:1092.0,   threebed:1296.45,  fourbed:1649.48  },
  'Richmond & Hambleton':       { shared:416.52,  onebed:448.76,   twobed:548.51,   threebed:648.22,   fourbed:827.71   },
  'Rotherham':                  { shared:350.35,  onebed:428.83,   twobed:498.64,   threebed:548.51,   fourbed:815.27   },
  'Rugby & East':               { shared:423.84,  onebed:593.36,   twobed:723.02,   threebed:847.69,   fourbed:1196.69  },
  'Salisbury':                  { shared:425.14,  onebed:648.22,   twobed:777.88,   threebed:912.51,   fourbed:1246.57  },
  'Scarborough':                { shared:308.97,  onebed:423.84,   twobed:548.51,   threebed:648.22,   fourbed:723.02   },
  'Scunthorpe':                 { shared:309.83,  onebed:408.89,   twobed:493.65,   threebed:573.43,   fourbed:723.02   },
  'Sheffield':                  { shared:349.05,  onebed:573.43,   twobed:618.28,   threebed:678.12,   fourbed:947.4    },
  'Shropshire':                 { shared:368.33,  onebed:473.72,   twobed:593.36,   threebed:723.02,   fourbed:972.31   },
  'Solihull':                   { shared:411.36,  onebed:698.1,    twobed:822.73,   threebed:997.27,   fourbed:1371.24  },
  'South Cheshire':             { shared:324.09,  onebed:473.72,   twobed:573.43,   threebed:678.12,   fourbed:992.29   },
  'South Devon':                { shared:366.17,  onebed:503.62,   twobed:673.14,   threebed:837.72,   fourbed:1096.98  },
  'South East Herts':           { shared:473.72,  onebed:832.69,   twobed:1047.11,  threebed:1366.26,  fourbed:1695.33  },
  'South West Essex':           { shared:475.02,  onebed:772.89,   twobed:947.4,    threebed:1196.69,  fourbed:1495.91  },
  'South West Herts':           { shared:499.94,  onebed:947.4,    twobed:1246.57,  threebed:1495.91,  fourbed:1994.5   },
  'Southampton':                { shared:423.84,  onebed:698.1,    twobed:872.6,    threebed:1072.07,  fourbed:1446.03  },
  'Southend':                   { shared:405.21,  onebed:678.12,   twobed:872.6,    threebed:1096.98,  fourbed:1346.28  },
  'Southern Greater Manchester':{ shared:410.45,  onebed:623.31,   twobed:747.93,   threebed:897.52,   fourbed:1396.16  },
  'Southport':                  { shared:368.33,  onebed:473.72,   twobed:598.35,   threebed:772.89,   fourbed:922.48   },
  'St Helens':                  { shared:323.87,  onebed:423.84,   twobed:523.55,   threebed:623.31,   fourbed:797.81   },
  'Staffordshire North':        { shared:300.52,  onebed:423.84,   twobed:478.7,    threebed:593.36,   fourbed:797.81   },
  'Stevenage & North Herts':    { shared:434.98,  onebed:772.89,   twobed:972.31,   threebed:1246.57,  fourbed:1595.62  },
  'Sunderland':                 { shared:320.45,  onebed:423.84,   twobed:473.72,   threebed:548.51,   fourbed:698.1    },
  'Sussex East':                { shared:360.01,  onebed:593.36,   twobed:747.93,   threebed:947.4,    fourbed:1146.86  },
  'Swindon':                    { shared:450.1,   onebed:673.14,   twobed:782.86,   threebed:947.4,    fourbed:1296.45  },
  'Tameside & Glossop':         { shared:320.19,  onebed:523.55,   twobed:598.35,   threebed:747.93,   fourbed:1146.86  },
  'Taunton & West Somerset':    { shared:403.0,   onebed:573.43,   twobed:723.02,   threebed:847.69,   fourbed:997.27   },
  'Teesside':                   { shared:288.17,  onebed:408.89,   twobed:473.72,   threebed:548.51,   fourbed:747.93   },
  'Thanet':                     { shared:378.95,  onebed:576.25,   twobed:747.93,   threebed:897.52,   fourbed:1146.86  },
  'Tyneside':                   { shared:380.29,  onebed:488.67,   twobed:548.51,   threebed:648.22,   fourbed:922.48   },
  'Wakefield':                  { shared:326.08,  onebed:498.64,   twobed:593.36,   threebed:723.02,   fourbed:882.57   },
  'Walton':                     { shared:618.28,  onebed:947.4,    twobed:1208.7,   threebed:1446.03,  fourbed:1969.59  },
  'Warwickshire South':         { shared:411.36,  onebed:698.1,    twobed:847.69,   threebed:1042.12,  fourbed:1346.28  },
  'West Cheshire':              { shared:374.83,  onebed:548.51,   twobed:673.14,   threebed:792.83,   fourbed:1220.66  },
  'West Cumbria':               { shared:318.93,  onebed:383.93,   twobed:473.72,   threebed:548.51,   fourbed:698.1    },
  'West Pennine':               { shared:309.83,  onebed:398.88,   twobed:448.76,   threebed:503.62,   fourbed:760.41   },
  'West Wiltshire':             { shared:448.76,  onebed:593.36,   twobed:723.02,   threebed:897.52,   fourbed:1196.69  },
  'Weston-S-Mare':              { shared:450.1,   onebed:578.41,   twobed:747.93,   threebed:922.48,   fourbed:1246.57  },
  'Wigan':                      { shared:338.91,  onebed:398.88,   twobed:498.64,   threebed:593.36,   fourbed:772.89   },
  'Winchester':                 { shared:523.55,  onebed:822.73,   twobed:1047.11,  threebed:1271.49,  fourbed:1695.33  },
  'Wirral':                     { shared:317.85,  onebed:423.84,   twobed:523.55,   threebed:648.22,   fourbed:822.73   },
  'Wolds and Coast':            { shared:343.42,  onebed:398.88,   twobed:493.65,   threebed:598.35,   fourbed:673.14   },
  'Worcester North':            { shared:328.94,  onebed:513.59,   twobed:648.22,   threebed:747.93,   fourbed:992.29   },
  'Worcester South':            { shared:381.55,  onebed:567.45,   twobed:698.1,    threebed:822.73,   fourbed:1146.86  },
  'Worthing':                   { shared:443.78,  onebed:757.9,    twobed:947.4,    threebed:1176.76,  fourbed:1460.98  },
  'Yeovil':                     { shared:433.81,  onebed:523.55,   twobed:693.12,   threebed:847.69,   fourbed:1246.57  },
  'York':                       { shared:416.52,  onebed:673.14,   twobed:772.89,   threebed:822.73,   fourbed:1196.69  },
}

// ---------------------------------------------------------------------------
// Local Authority name (postcodes.io admin_district) → BRMA name.
// Covers ~250 LAs.  Unmapped LAs fall back to the regional estimate in rates.js.
// ---------------------------------------------------------------------------
const LA_TO_BRMA = {
  // ── London boroughs ───────────────────────────────────────────────────────
  'City of London':            'Central London',
  'Westminster':               'Central London',
  'Kensington and Chelsea':    'Central London',
  'Camden':                    'Inner North London',
  'Islington':                 'Inner North London',
  'Hackney':                   'Inner East London',
  'Tower Hamlets':             'Inner East London',
  'Newham':                    'Inner East London',
  'Southwark':                 'Inner South East London',
  'Lewisham':                  'Inner South East London',
  'Lambeth':                   'Inner South West London',
  'Wandsworth':                'Inner South West London',
  'Hammersmith and Fulham':    'Inner West London',
  'Brent':                     'North West London',
  'Harrow':                    'North West London',
  'Barnet':                    'Outer North London',
  'Enfield':                   'Outer North London',
  'Haringey':                  'Outer North London',
  'Waltham Forest':            'Outer North East London',
  'Redbridge':                 'Outer East London',
  'Barking and Dagenham':      'Outer East London',
  'Havering':                  'Outer East London',
  'Bexley':                    'Outer South East London',
  'Greenwich':                 'Outer South East London',
  'Bromley':                   'Outer South London',
  'Croydon':                   'Outer South London',
  'Sutton':                    'Outer South London',
  'Merton':                    'Outer South West London',
  'Kingston upon Thames':      'Outer South West London',
  'Richmond upon Thames':      'Outer West London',
  'Hounslow':                  'Outer West London',
  'Ealing':                    'Outer West London',
  'Hillingdon':                'Outer West London',

  // ── Near-London / Home Counties ──────────────────────────────────────────
  'Slough':                    'East Thames Valley',
  'Windsor and Maidenhead':    'East Thames Valley',
  'Spelthorne':                'East Thames Valley',
  'Runnymede':                 'East Thames Valley',
  'Elmbridge':                 'Walton',
  'Epsom and Ewell':           'Walton',
  'Mole Valley':               'Walton',
  'Tandridge':                 'Crawley & Reigate',
  'Reigate and Banstead':      'Crawley & Reigate',
  'Crawley':                   'Crawley & Reigate',
  'Mid Sussex':                'High Weald',
  'Tunbridge Wells':           'High Weald',
  'Sevenoaks':                 'North West Kent',
  'Dartford':                  'North West Kent',
  'Gravesham':                 'North West Kent',
  'Tonbridge and Malling':     'Maidstone',
  'Maidstone':                 'Maidstone',
  'Medway':                    'Medway & Swale',
  'Swale':                     'Medway & Swale',
  'Canterbury':                'Canterbury',
  'Thanet':                    'Thanet',
  'Dover':                     'Dover-Shepway',
  'Folkestone and Hythe':      'Dover-Shepway',
  'Ashford':                   'Ashford',
  'Eastbourne':                'Eastbourne',
  'Hastings':                  'Eastbourne',
  'Lewes':                     'Brighton and Hove',
  'Brighton and Hove':         'Brighton and Hove',
  'Worthing':                  'Worthing',
  'Adur':                      'Worthing',
  'Arun':                      'Chichester',
  'Chichester':                'Chichester',
  'East Sussex':               'Sussex East',
  'Rother':                    'Sussex East',
  'Wealden':                   'Sussex East',

  // ── South East / Thames Valley ───────────────────────────────────────────
  'Guildford':                 'Guildford',
  'Waverley':                  'Guildford',
  'Woking':                    'Guildford',
  'Surrey Heath':              'Blackwater Valley',
  'Hart':                      'Blackwater Valley',
  'Rushmoor':                  'Blackwater Valley',
  'Basingstoke and Deane':     'Basingstoke',
  'Test Valley':               'Southampton',
  'Southampton':               'Southampton',
  'Eastleigh':                 'Southampton',
  'Fareham':                   'Portsmouth',
  'Gosport':                   'Portsmouth',
  'Portsmouth':                'Portsmouth',
  'Havant':                    'Portsmouth',
  'Winchester':                'Winchester',
  'New Forest':                'Southampton',
  'Isle of Wight':             'Isle of Wight',
  'Reading':                   'Reading',
  'Wokingham':                 'Reading',
  'Bracknell Forest':          'Blackwater Valley',
  'West Berkshire':            'Newbury',
  'Oxford':                    'Oxford',
  'South Oxfordshire':         'Oxford',
  'Vale of White Horse':       'Oxford',
  'West Oxfordshire':          'Cherwell Valley',
  'Cherwell':                  'Cherwell Valley',
  'Aylesbury Vale':            'Aylesbury',
  'Chiltern':                  'Chilterns',
  'South Bucks':               'Chilterns',
  'Wycombe':                   'Chilterns',
  'Milton Keynes':             'Milton Keynes',
  'Buckinghamshire':           'Aylesbury',

  // ── East of England ──────────────────────────────────────────────────────
  'Hertsmere':                 'South West Herts',
  'Three Rivers':              'South West Herts',
  'Watford':                   'South West Herts',
  'St Albans':                 'South West Herts',
  'Dacorum':                   'South West Herts',
  'Welwyn Hatfield':           'South East Herts',
  'Broxbourne':                'South East Herts',
  'East Hertfordshire':        'Harlow & Stortford',
  'Harlow':                    'Harlow & Stortford',
  'Epping Forest':             'South West Essex',
  'Chelmsford':                'Chelmsford',
  'Brentwood':                 'Chelmsford',
  'Basildon':                  'South West Essex',
  'Thurrock':                  'South West Essex',
  'Southend-on-Sea':           'Southend',
  'Castle Point':              'Southend',
  'Rochford':                  'Southend',
  'Colchester':                'Colchester',
  'Tendring':                  'Colchester',
  'Braintree':                 'Chelmsford',
  'Maldon':                    'Chelmsford',
  'Uttlesford':                'Harlow & Stortford',
  'Luton':                     'Luton',
  'Central Bedfordshire':      'Bedford',
  'Bedford':                   'Bedford',
  'North Hertfordshire':       'Stevenage & North Herts',
  'Stevenage':                 'Stevenage & North Herts',
  'Cambridge':                 'Cambridge',
  'South Cambridgeshire':      'Cambridge',
  'East Cambridgeshire':       'Cambridge',
  'Huntingdonshire':           'Huntingdon',
  'Fenland':                   'Huntingdon',
  'Peterborough':              'Peterborough',
  'Ipswich':                   'Ipswich',
  'Babergh':                   'Ipswich',
  'Mid Suffolk':               'Bury St Edmunds',
  'West Suffolk':              'Bury St Edmunds',
  'Kings Lynn and West Norfolk': 'Kings Lynn',
  'North Norfolk':             'Central Norfolk & Norwich',
  'Norwich':                   'Central Norfolk & Norwich',
  'Broadland':                 'Central Norfolk & Norwich',
  'South Norfolk':             'Central Norfolk & Norwich',
  'Breckland':                 'Central Norfolk & Norwich',
  'Great Yarmouth':            'Lowestoft & Great Yarmouth',
  'Waveney':                   'Lowestoft & Great Yarmouth',
  'Suffolk Coastal':           'Ipswich',

  // ── East Midlands ────────────────────────────────────────────────────────
  'Leicester':                 'Leicester',
  'Oadby and Wigston':         'Leicester',
  'Blaby':                     'Leicester',
  'Charnwood':                 'Leicester',
  'Hinckley and Bosworth':     'Leicester',
  'Harborough':                'Leicester',
  'Melton':                    'Grantham & Newark',
  'Nottingham':                'Nottingham',
  'Broxtowe':                  'Nottingham',
  'Gedling':                   'Nottingham',
  'Rushcliffe':                'Nottingham',
  'Hucknall':                  'North Nottingham',
  'Ashfield':                  'North Nottingham',
  'Mansfield':                 'North Nottingham',
  'Newark and Sherwood':       'Grantham & Newark',
  'Basford':                   'North Nottingham',
  'Derby':                     'Derby',
  'Erewash':                   'Derby',
  'Amber Valley':              'Derby',
  'South Derbyshire':          'Derby',
  'Derbyshire Dales':          'Peaks & Dales',
  'High Peak':                 'Peaks & Dales',
  'Chesterfield':              'Chesterfield',
  'North East Derbyshire':     'Chesterfield',
  'Bolsover':                  'Chesterfield',
  'Lincoln':                   'Lincoln',
  'North Lincolnshire':        'Scunthorpe',
  'North East Lincolnshire':   'Grimsby',
  'Lincoln City':              'Lincoln',
  'West Lindsey':              'Lincoln',
  'East Lindsey':              'Wolds and Coast',
  'Boston':                    'Lincolnshire Fens',
  'South Holland':             'Lincolnshire Fens',
  'South Kesteven':            'Grantham & Newark',
  'North Kesteven':            'Lincoln',
  'Northampton':               'Northampton',
  'West Northamptonshire':     'Northampton',
  'North Northamptonshire':    'Northants Central',
  'Kettering':                 'Northants Central',
  'Corby':                     'Northants Central',
  'Daventry':                  'Northants Central',
  'Wellingborough':            'Northants Central',

  // ── West Midlands ────────────────────────────────────────────────────────
  'Birmingham':                'Birmingham',
  'Coventry':                  'Coventry',
  'Wolverhampton':             'Black Country',
  'Dudley':                    'Black Country',
  'Sandwell':                  'Black Country',
  'Walsall':                   'Black Country',
  'Solihull':                  'Solihull',
  'Warwick':                   'Warwickshire South',
  'Stratford-on-Avon':        'Warwickshire South',
  'Leamington':                'Warwickshire South',
  'Rugby':                     'Rugby & East',
  'Nuneaton and Bedworth':     'Rugby & East',
  'North Warwickshire':        'Rugby & East',
  'Lichfield':                 'Eastern Staffordshire',
  'Tamworth':                  'Eastern Staffordshire',
  'Cannock Chase':             'Eastern Staffordshire',
  'Burton upon Trent':         'Eastern Staffordshire',
  'East Staffordshire':        'Eastern Staffordshire',
  'Stafford':                  'Mid Staffs',
  'South Staffordshire':       'Mid Staffs',
  'Stoke-on-Trent':            'Staffordshire North',
  'Newcastle-under-Lyme':      'Staffordshire North',
  'Staffordshire Moorlands':   'Staffordshire North',
  'Telford and Wrekin':        'Shropshire',
  'Shropshire':                'Shropshire',
  'Herefordshire':             'Herefordshire',
  'Worcester':                 'Worcester North',
  'Wychavon':                  'Worcester North',
  'Malvern Hills':             'Worcester South',
  'Bromsgrove':                'Worcester South',
  'Redditch':                  'Worcester South',
  'Cheltenham':                'Cheltenham',
  'Gloucester':                'Gloucester',
  'Forest of Dean':            'Gloucester',
  'Cotswold':                  'Cheltenham',
  'Stroud':                    'Gloucester',
  'Tewkesbury':                'Cheltenham',

  // ── Yorkshire & Humber ───────────────────────────────────────────────────
  'Leeds':                     'Leeds',
  'Bradford':                  'Bradford & South Dales',
  'Kirklees':                  'Kirklees',
  'Calderdale':                'Halifax',
  'Wakefield':                 'Wakefield',
  'Sheffield':                 'Sheffield',
  'Doncaster':                 'Doncaster',
  'Rotherham':                 'Rotherham',
  'Barnsley':                  'Barnsley',
  'Hull':                      'Hull & East Riding',
  'Kingston upon Hull':        'Hull & East Riding',
  'East Riding of Yorkshire':  'Hull & East Riding',
  'York':                      'York',
  'Scarborough':               'Scarborough',
  'Ryedale':                   'Scarborough',
  'Selby':                     'York',
  'Harrogate':                 'Harrogate',
  'Hambleton':                 'Richmond & Hambleton',
  'Richmondshire':             'Richmond & Hambleton',
  'Craven':                    'Bradford & South Dales',
  'Grimsby':                   'Grimsby',

  // ── North East ───────────────────────────────────────────────────────────
  'Newcastle upon Tyne':       'Tyneside',
  'Gateshead':                 'Tyneside',
  'South Tyneside':            'Tyneside',
  'North Tyneside':            'Tyneside',
  'Sunderland':                'Sunderland',
  'Middlesbrough':             'Teesside',
  'Stockton-on-Tees':         'Teesside',
  'Hartlepool':                'Teesside',
  'Redcar and Cleveland':      'Teesside',
  'Darlington':                'Darlington',
  'Durham':                    'Durham',
  'County Durham':             'Durham',
  'Northumberland':            'Northumberland',

  // ── North West ───────────────────────────────────────────────────────────
  'Manchester':                'Central Greater Manchester',
  'Salford':                   'Central Greater Manchester',
  'Trafford':                  'Southern Greater Manchester',
  'Stockport':                 'Southern Greater Manchester',
  'Bolton':                    'Bolton and Bury',
  'Bury':                      'Bolton and Bury',
  'Wigan':                     'Wigan',
  'Oldham':                    'Oldham & Rochdale',
  'Rochdale':                  'Oldham & Rochdale',
  'Tameside':                  'Tameside & Glossop',
  'High Peak':                 'Tameside & Glossop',
  'Liverpool':                 'Greater Liverpool',
  'Knowsley':                  'Greater Liverpool',
  'Sefton':                    'Greater Liverpool',
  'St. Helens':                'St Helens',
  'Halton':                    'St Helens',
  'Wirral':                    'Wirral',
  'West Lancashire':           'Southport',
  'Southport':                 'Southport',
  'Preston':                   'Central Lancs',
  'South Ribble':              'Central Lancs',
  'Chorley':                   'Central Lancs',
  'Burnley':                   'East Lancs',
  'Hyndburn':                  'East Lancs',
  'Pendle':                    'East Lancs',
  'Ribble Valley':             'East Lancs',
  'Rossendale':                'East Lancs',
  'Blackburn with Darwen':     'East Lancs',
  'Blackpool':                 'Fylde Coast',
  'Fylde':                     'Fylde Coast',
  'Wyre':                      'Fylde Coast',
  'Lancaster':                 'Lancaster',
  'Morecambe':                 'Lancaster',
  'Cheshire East':             'East Cheshire',
  'Macclesfield':              'East Cheshire',
  'Warrington':                'North Cheshire',
  'Cheshire West and Chester': 'West Cheshire',
  'Chester':                   'West Cheshire',
  'Cumbria':                   'North Cumbria',
  'Carlisle':                  'North Cumbria',
  'Eden':                      'North Cumbria',
  'Copeland':                  'West Cumbria',
  'Allerdale':                 'West Cumbria',
  'Barrow-in-Furness':         'Barrow-in-Furness',
  'South Lakeland':            'Kendal',
  'Westmorland and Furness':   'Kendal',
  'Cumberland':                'North Cumbria',

  // ── South West ───────────────────────────────────────────────────────────
  'Bristol':                   'Bristol',
  'Bath and North East Somerset': 'Bath',
  'South Gloucestershire':     'Bristol',
  'North Somerset':            'Weston-S-Mare',
  'Somerset':                  'Taunton & West Somerset',
  'Taunton Deane':             'Taunton & West Somerset',
  'West Somerset':             'Taunton & West Somerset',
  'Sedgemoor':                 'Taunton & West Somerset',
  'Mendip':                    'Mendip',
  'Yeovil':                    'Yeovil',
  'South Somerset':            'Yeovil',
  'Swindon':                   'Swindon',
  'Wiltshire':                 'West Wiltshire',
  'Salisbury':                 'Salisbury',
  'South Wiltshire':           'Salisbury',
  'Exeter':                    'Exeter',
  'East Devon':                'Mid & East Devon',
  'Teignbridge':               'South Devon',
  'Torbay':                    'South Devon',
  'South Hams':                'South Devon',
  'Plymouth':                  'Plymouth',
  'North Devon':               'North Devon',
  'Mid Devon':                 'Mid & East Devon',
  'Torridge':                  'North Cornwall & Devon Borders',
  'West Devon':                'North Cornwall & Devon Borders',
  'Bournemouth':               'Bournemouth',
  'Poole':                     'Bournemouth',
  'Christchurch':              'Bournemouth',
  'Bournemouth, Christchurch and Poole': 'Bournemouth',
  'Dorset':                    'Mid & West Dorset',
  'East Dorset':               'Bournemouth',
  'North Dorset':              'Mid & West Dorset',
  'West Dorset':               'Mid & West Dorset',
  'Weymouth and Portland':     'Mid & West Dorset',
  'Cornwall':                  'Kernow West',
  'Isles of Scilly':           'Kernow West',

  // ── East / South East misc ───────────────────────────────────────────────
  'Hastings':                  'Eastbourne',
  'Norwich':                   'Central Norfolk & Norwich',
  'Hereford':                  'Herefordshire',
}

// ---------------------------------------------------------------------------
// Bedroom entitlement rules (DWP LHA category).
// Under-35 single with no children → shared accommodation rate (CAT A).
// ---------------------------------------------------------------------------
function getBedroomCat(answers) {
  const { age, children, situation } = answers || {}
  const noChildren = !children || children === 'No children'
  const under35 = age === 'Under 25' || age === '25 to 34'
  const isCarer  = situation === 'Carer for someone'

  if (under35 && noChildren && !isCarer) return 'shared'  // CAT A — shared accommodation
  if (noChildren)                         return 'onebed'  // CAT B — 1 bedroom
  if (children === '1 child' || children === '2 children') return 'twobed'   // CAT C
  return 'threebed'                                        // CAT D — 3 or more children
}

// Map CAT key to monthly LHA rate
function pickRate(brmaRates, cat) {
  return brmaRates[cat] ?? brmaRates.onebed
}

// ---------------------------------------------------------------------------
// HTTP handler
// ---------------------------------------------------------------------------
exports.handler = async (event) => {
  const headers = { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }

  const params  = event.queryStringParameters || {}
  const rawCode = params.postcode
  if (!rawCode) {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'postcode parameter required' }) }
  }

  const postcode = rawCode.replace(/\s+/g, '').toUpperCase()

  // Basic UK postcode format check
  if (!/^[A-Z]{1,2}[0-9][0-9A-Z]?[0-9][A-Z]{2}$/.test(postcode)) {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid postcode format' }) }
  }

  let councilName, region
  try {
    const res  = await fetch(`https://api.postcodes.io/postcodes/${postcode}`)
    const json = await res.json()

    if (json.status !== 200 || !json.result) {
      return { statusCode: 404, headers, body: JSON.stringify({ error: 'Postcode not found' }) }
    }

    councilName = json.result.admin_district
    region      = json.result.region  // null for Scotland
  } catch (err) {
    console.error('postcodes.io error:', err.message)
    return { statusCode: 502, headers, body: JSON.stringify({ error: 'Postcode lookup service unavailable' }) }
  }

  const brmaName  = LA_TO_BRMA[councilName]
  const brmaRates = brmaName ? BRMA_RATES[brmaName] : null

  // Build answers object from optional query params so we can determine bedroom category
  const answers = {
    age:       params.age,
    children:  params.children,
    situation: params.situation,
  }
  const bedroomCat  = getBedroomCat(answers)
  const lhaMonthly  = brmaRates ? parseFloat(pickRate(brmaRates, bedroomCat).toFixed(2)) : null

  return {
    statusCode: 200,
    headers,
    body: JSON.stringify({
      postcode,
      councilName:  councilName || null,
      region:       region      || null,
      brma:         brmaName    || null,
      bedroomCat,
      lhaMonthly,
      allRates:     brmaRates   || null,
      found:        !!brmaRates,
    }),
  }
}

// Also export helpers for use by calculate-benefits.js
module.exports.getBedroomCat = getBedroomCat
module.exports.BRMA_RATES    = BRMA_RATES
module.exports.LA_TO_BRMA    = LA_TO_BRMA
